server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
        routes:
          - id: auth-service
            uri: http://auth-service:8081
            predicates:
              - Path=/api/auth/**,/api/users/**
          - id: transaction-service
            uri: http://transaction-service:8082
            predicates:
              - Path=/api/accounts/**,/api/transactions/**
          - id: review-service
            uri: http://review-service:8084
            predicates:
              - Path=/api/reviews/**
          - id: fraud-service
            uri: http://fraud-service:8083
            predicates:
              - Path=/api/fraud/**

gateway:
  security:
    jwt:
      issuer: fraudwatch-auth-service
      secret: ZmFrZS1mcmF1ZHdhdGNoLWRldi1zZWNyZXQtZmFrZS1mcmF1ZHdhdGNoLWRldi1zZWNyZXQ=
